server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: api-authentication
          uri: lb://API-AUTHENTICATION
          predicates:
            - Path=/auth/**

        - id: reservation-service
          uri: lb://RESERVATION-SERVICE
          predicates:
            - Path=/reservations/**
          filters:
            - RewritePath=/reservations/(?<segment>.*), /${segment}

        - id: restaurant-service
          uri: lb://RESTAURANT-SERVICE
          predicates:
            - Path=/restaurants/**
          filters:
            - RewritePath=/restaurants/(?<segment>.*), /${segment}

    loadbalancer:
      retry:
        enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
